# Generated by Django 5.2.8 on 2025-12-16 16:57

import django.db.models.deletion
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_payment_transaction_id_alter_payment_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NEW_TaxExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_exempt', models.BooleanField(default=False, help_text='Whether user is tax exempt')),
                ('exemption_type', models.CharField(blank=True, choices=[('resale', 'Resale Certificate'), ('nonprofit', 'Non-Profit Organization'), ('government', 'Government Entity'), ('other', 'Other')], help_text='Type of tax exemption', max_length=50)),
                ('certificate_number', models.CharField(blank=True, help_text='Exemption certificate number', max_length=100)),
                ('certificate_file', models.FileField(blank=True, help_text='Upload exemption certificate', upload_to='tax_exemptions/')),
                ('effective_date', models.DateField(blank=True, help_text='Date exemption becomes effective', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Date exemption expires', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about this exemption')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_exemption', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NEW Tax Exemption',
                'verbose_name_plural': 'NEW Tax Exemptions',
            },
        ),
        migrations.CreateModel(
            name='NEW_TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, help_text='0.0875 = 8.75%', max_digits=5)),
                ('tax_type', models.CharField(choices=[('sales', 'Sales Tax'), ('use', 'Use Tax'), ('excise', 'Excise Tax'), ('property', 'Property Tax'), ('income', 'Income Tax'), ('other', 'Other')], default='sales', max_length=50)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='state', chained_model_field='state', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='NEW_tax_calculator.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='NEW_tax_calculator.country')),
            ],
            options={
                'verbose_name': 'NEW Tax Rate',
                'verbose_name_plural': 'NEW Tax Rates',
                'ordering': ['country', 'state', 'city', '-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='NEW_TaxCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxable_amount', models.DecimalField(decimal_places=2, help_text='Amount subject to tax', max_digits=10)),
                ('tax_rate_value', models.DecimalField(decimal_places=4, help_text='Tax rate applied', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, help_text='Calculated tax amount', max_digits=10)),
                ('is_exempt', models.BooleanField(default=False, help_text='Whether this calculation was exempt')),
                ('exemption_reason', models.CharField(blank=True, help_text='Reason for exemption', max_length=200)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_calculations', to='cart.order')),
                ('tax_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEW_tax_calculator.new_taxrate')),
            ],
            options={
                'verbose_name': 'NEW Tax Calculation',
                'verbose_name_plural': 'NEW Tax Calculations',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='NEW_tax_calculator.country')),
            ],
            options={
                'verbose_name_plural': 'States',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='new_taxrate',
            name='state',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='NEW_tax_calculator.state'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='NEW_tax_calculator.state'),
        ),
    ]
