# Generated by Django 5.2.8 on 2025-12-30 17:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Write your blog post content here. Use the toolbar above to format text, add headings, lists, and more. No HTML knowledge needed!'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Write a short summary (2-3 sentences) that will appear on the blog listing page', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(help_text="Enter the title of your blog post (e.g., 'Welcome to Our Blog')", max_length=200),
        ),
    ]
