# Generated by Django 5.2.8 on 2025-12-31 06:27

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_content_alter_blogpost_excerpt_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text="Add tags to categorize your blog post (e.g., 'hardwood', 'furniture', 'sculptures')", through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
