# Generated by Django 5.2.8 on 2025-12-23 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0003_alter_address_address_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NEW_WholesaleDiscountConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name', max_length=100)),
                ('threshold_1', models.DecimalField(decimal_places=2, default=500.0, help_text='First threshold amount (e.g., $500)', max_digits=10)),
                ('discount_1', models.DecimalField(decimal_places=2, default=10.0, help_text='First discount percentage (e.g., 10%)', max_digits=5)),
                ('threshold_2', models.DecimalField(decimal_places=2, default=1000.0, help_text='Second threshold amount (e.g., $1000)', max_digits=10)),
                ('discount_2', models.DecimalField(decimal_places=2, default=15.0, help_text='Second discount percentage (e.g., 15%)', max_digits=5)),
                ('threshold_3', models.DecimalField(decimal_places=2, default=2000.0, help_text='Third threshold amount (e.g., $2000)', max_digits=10)),
                ('discount_3', models.DecimalField(decimal_places=2, default=20.0, help_text='Third discount percentage (e.g., 20%)', max_digits=5)),
                ('threshold_4', models.DecimalField(decimal_places=2, default=2500.0, help_text='Fourth threshold amount (e.g., $2500)', max_digits=10)),
                ('discount_4', models.DecimalField(decimal_places=2, default=25.0, help_text='Fourth discount percentage (e.g., 25%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wholesale Discount Configuration',
                'verbose_name_plural': 'Wholesale Discount Configurations',
            },
        ),
        migrations.CreateModel(
            name='NEW_WholesaleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('retailer', 'Retailer'), ('distributor', 'Distributor'), ('reseller', 'Reseller'), ('contractor', 'Contractor'), ('nonprofit', 'Non-Profit Organization'), ('other', 'Other')], help_text='Type of business', max_length=100)),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID or EIN', max_length=50)),
                ('website', models.URLField(blank=True, help_text='Business website')),
                ('expected_monthly_volume', models.TextField(help_text='Expected monthly order volume')),
                ('reason', models.TextField(help_text='Why do you need wholesale access?')),
                ('documents', models.FileField(blank=True, null=True, upload_to='wholesale_documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin review notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_wholesale_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wholesale Request',
                'verbose_name_plural': 'Wholesale Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NEW_WholesaleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_wholesale', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this wholesale user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_wholesale_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wholesale User',
                'verbose_name_plural': 'Wholesale Users',
            },
        ),
        migrations.CreateModel(
            name='NEW_WholesaleDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount percentage or amount', max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Actual discount amount applied', max_digits=10)),
                ('order_amount', models.DecimalField(decimal_places=2, help_text='Order amount before discount', max_digits=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_discounts', to='cart.order')),
                ('wholesale_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEW_wholesale_discounts.new_wholesaleuser')),
            ],
            options={
                'verbose_name': 'Wholesale Discount',
                'verbose_name_plural': 'Wholesale Discounts',
                'ordering': ['-applied_at'],
            },
        ),
    ]
