# Generated by Django 5.2.8 on 2025-11-29 07:07

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='categories/images/small/')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='galleryItem.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='SEO-friendly URL (auto-generated from title)', max_length=300, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('metaKeyWords', models.CharField(help_text='comma delimitted set of SEO keywords', max_length=255)),
                ('metaKeyDescription', models.CharField(help_text='content for description meta tag', max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleryItem.category')),
                ('google_product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galleryItem.googleproductcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('date_added', models.DateTimeField()),
                ('featured', models.BooleanField(default=False)),
                ('keep_anonymous', models.BooleanField(default=False)),
                ('is_imported', models.BooleanField(default=False)),
                ('import_order_id', models.IntegerField(null=True)),
                ('import_author', models.CharField(blank=True, max_length=255)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='galleryItem.galleryitem')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calculation_type', models.CharField(choices=[('addition', 'Addition'), ('subtraction', 'Subtraction'), ('multiplication', 'Multiplication'), ('division', 'Division')], max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleryItem.galleryitem')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='supply/images/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleryItem.supplier')),
            ],
            options={
                'verbose_name_plural': 'Supplies',
            },
        ),
        migrations.CreateModel(
            name='TransferedReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('date_added', models.DateTimeField()),
                ('featured', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfered_reviews', to='galleryItem.galleryitem')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/small/')),
                ('largeImage', models.ImageField(upload_to='products/images/large/')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('quantity', models.IntegerField()),
                ('volume', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('is_best_seller', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleryItem.galleryitem')),
            ],
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='default_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='galleryItem.variant'),
        ),
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='products/images/')),
                ('featured', models.BooleanField(default=False)),
                ('thumbnail', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleryItem.variant')),
            ],
        ),
        migrations.CreateModel(
            name='VariantSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleryItem.supply')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleryItem.variant')),
            ],
            options={
                'verbose_name_plural': 'Variant Supply',
                'unique_together': {('variant', 'supply')},
            },
        ),
        migrations.AddField(
            model_name='variant',
            name='supplies',
            field=models.ManyToManyField(related_name='variant_supply', through='galleryItem.VariantSupply', to='galleryItem.supply'),
        ),
        migrations.CreateModel(
            name='VariantVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='products/videos/')),
                ('thumbnail_image', models.ImageField(upload_to='products/videos/thumbnail_images/')),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleryItem.variant')),
            ],
        ),
        migrations.CreateModel(
            name='VariantYoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('youtube_video_code', models.CharField(max_length=255)),
                ('thumbnail_image', models.ImageField(upload_to='products/youtube_video/thumbnail_images/')),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleryItem.variant')),
            ],
        ),
        migrations.CreateModel(
            name='WishedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_unwished', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleryItem.galleryitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(choices=[('F', 'Most Favorited'), ('V', 'Most Viewed'), ('S', 'Most Sold')], max_length=1)),
                ('value', models.PositiveIntegerField()),
                ('rank', models.PositiveIntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleryItem.galleryitem')),
            ],
            options={
                'unique_together': {('criteria', 'product', 'date_added')},
            },
        ),
    ]
