# Generated by Django 5.2.8 on 2025-11-29 07:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galleryItem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount_type', models.CharField(choices=[('fixed_amount', 'Fixed Amount'), ('percentage', 'Percentage')], max_length=15)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('single_use_per_user', models.BooleanField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(choices=[('V', 'Volume'), ('W', 'Weight')], max_length=1)),
                ('value_start', models.PositiveIntegerField()),
                ('value_end', models.PositiveIntegerField()),
                ('shipment_type', models.CharField(choices=[('L', 'Local'), ('OC', 'Other City'), ('OS', 'Other State'), ('I', 'International')], max_length=2)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=16)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('address_line_1', models.CharField(max_length=150)),
                ('address_line_2', models.CharField(blank=True, max_length=150)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('address_type', models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1)),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time cart was modified')),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('N', 'Not finalized yet'), ('O', 'Not shipped yet'), ('S', 'Shipped'), ('D', 'Delivered'), ('C', 'Canceled')], default='N', max_length=1)),
                ('total_shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='NEW: Tax amount for this order', max_digits=10)),
                ('wholesale_discount', models.DecimalField(decimal_places=2, default=0, help_text='NEW: Wholesale discount amount', max_digits=10)),
                ('is_tax_exempt', models.BooleanField(default=False, help_text='NEW: Whether this order is tax exempt')),
                ('abandoned_email_sent', models.BooleanField(default=False, help_text='Whether abandoned cart email has been sent')),
                ('abandoned_email_sent_at', models.DateTimeField(blank=True, help_text='When abandoned cart email was sent', null=True)),
                ('abandoned_email_count', models.IntegerField(default=0, help_text='Number of abandoned cart emails sent')),
                ('recovery_link_clicked_at', models.DateTimeField(blank=True, help_text='When user clicked recovery link from email (delays next email)', null=True)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='cart.address')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.coupon')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='cart.address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.order')),
                ('special_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galleryItem.specialprice')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleryItem.variant')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('P', 'PayPal')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('successful', models.BooleanField(default=False)),
                ('amount', models.FloatField()),
                ('raw_response', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cart.order')),
            ],
        ),
    ]
