# Generated by Django 5.2.8 on 2025-12-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Payment gateway transaction ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('P', 'PayPal'), ('S', 'Stripe')], max_length=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='raw_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
