# Generated by Django 5.2.8 on 2025-12-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_payment_transaction_id_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping'), ('H', 'Home'), ('W', 'Work')], max_length=1),
        ),
    ]
